version: '3.5'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - kerb
    restart: unless-stopped

  kerb-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kerb-app
    networks:
      - kerb
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./:/var/www/html/"
      - "./conf/php:/usr/local/etc/php/"
      - "./conf/apache:/etc/apache2/sites-enabled/"

networks:
  kerb:
    driver: bridge
